
services:
  redis:
    image: redis:7.2-alpine
    container_name: chime6-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always

volumes:
  redis_data:
